---
# Cluster-Oriented Deployment ApplicationSet
# Creates Applications only when deployment marker files exist
# File path: deployments/{region}/{cluster}/{codebase}.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{.Values.clusterName}}-applications'
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    # Two-generator Matrix for selective deployment
    - matrix:
        generators:
          # Generator 1: Scan deployment marker files
          # Path structure: deployments/{region}/{cluster}/{codebase}.yaml
          # Provides: region (path[1]), cluster (path[2]), codebase (filename), cluster config (file content)
          - git:
              repoURL: '{{.Values.repoURL}}'
              revision: '{{.Values.revision}}'
              files:
                - path: 'deployments/{{.Values.region}}/{{.Values.clusterName}}/*.yaml'

          # Generator 2: Load codebase configuration
          # Uses codebase name from Generator 1 to load the right codebase.yaml
          - git:
              repoURL: '{{.Values.repoURL}}'
              revision: '{{.Values.revision}}'
              files:
                - path: 'codebases/{{.path.basenameNormalized}}/codebase.yaml'

  template:
    metadata:
      # Application name: <cluster>-<codebase>
      # path[2] = cluster name (e.g., euc1-dev)
      # path.basenameNormalized = codebase name (e.g., frontend-app)
      name: '{{.path[2]}}-{{.path.basenameNormalized}}'
      labels:
        codebase: '{{.path.basenameNormalized}}'
        cluster: '{{.path[2]}}'
        region: '{{.path[1]}}'
        environment: '{{.cluster.environment}}'
      # Finalizers ensure proper cleanup
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      sources:
        # Source 1: Remote Helm chart from codebase repository
        - repoURL: '{{.codebase.repoURL}}'
          # Version resolution priority:
          # 1. deployment.targetRevision (override from deployment file)
          # 2. codebase.targetRevisions[region][environment] (from codebase.yaml matrix)
          targetRevision: '{{if .deployment.targetRevision}}{{.deployment.targetRevision}}{{else}}{{index (index .codebase.targetRevisions .path[1]) .cluster.environment}}{{end}}'
          path: '{{.codebase.chartPath}}'
          helm:
            # Override release name to use short codebase name instead of full Application name
            # This keeps Helm release names clean (e.g., "frontend-app" instead of "euc1-dev-frontend-app")
            releaseName: '{{.path.basenameNormalized}}'
            valueFiles:
              - values.yaml  # Default values from the remote chart
              # Reference values from this repository (second source)
              # Path: codebases/{codebase}/values/{region}/{environment}.yaml
              - $values/codebases/{{.path.basenameNormalized}}/values/{{.path[1]}}/{{.cluster.environment}}.yaml

        # Source 2: Values overrides from this repository
        - repoURL: '{{.Values.repoURL}}'
          targetRevision: '{{.Values.revision}}'
          ref: values

      destination:
        server: '{{.cluster.server}}'
        namespace: '{{.codebase.namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      # Health checks
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
