# Values overrides for frontend-app in staging cluster

image:
  tag: "v1.2.3"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: true
  host: frontend-staging.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging

env:
  - name: ENVIRONMENT
    value: "staging"
  - name: API_URL
    value: "https://api-staging.example.com"
  - name: LOG_LEVEL
    value: "info"

features:
  analytics: true
  experimental: true
