# Values overrides for backend-api in dev cluster

image:
  tag: "dev-latest"
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  - name: ENVIRONMENT
    value: "development"
  - name: DATABASE_HOST
    value: "postgres-dev.default.svc.cluster.local"
  - name: LOG_LEVEL
    value: "debug"
  - name: ENABLE_SWAGGER
    value: "true"

# Service configuration
service:
  type: ClusterIP
  port: 8080
