# Values overrides for backend-api in prod cluster

image:
  tag: "v2.1.0"
  pullPolicy: IfNotPresent

replicaCount: 4

resources:
  limits:
    cpu: 4000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 1Gi

env:
  - name: ENVIRONMENT
    value: "production"
  - name: DATABASE_HOST
    value: "postgres-prod.default.svc.cluster.local"
  - name: LOG_LEVEL
    value: "warn"
  - name: ENABLE_SWAGGER
    value: "false"

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 2
